# Sonar reading

In [1]:
import pandas as pd
import numpy as np

In [2]:
sonar = np.loadtxt("./day01_input.txt")

### Part 1: How many measurements are larger than the previous measurement?

In [3]:
test = np.array([199, 200, 208, 210, 200, 207, 240, 269, 260, 263])

In [4]:
test

array([199, 200, 208, 210, 200, 207, 240, 269, 260, 263])

In [5]:
np.sum(test[1:] > test[:-1])

7

Looks solid

In [6]:
np.sum(sonar[1:] > sonar[:-1])

1477

### Part 2: the same, but now in sliding windows of window size = 3

```
199  A      
200  A B    
208  A B C  
210    B C D
200  E   C D
207  E F   D
240  E F G  
269    F G H
260      G H
263        H
```

Start by comparing the first and second three-measurement windows. The measurements in the first window are marked A (199, 200, 208); their sum is 199 + 200 + 208 = 607. The second window is marked B (200, 208, 210); its sum is 618. The sum of measurements in the second window is larger than the sum of the first, so this first comparison increased.

Your goal now is to count the number of times the sum of measurements in this sliding window increases from the previous sum. So, compare A with B, then compare B with C, then C with D, and so on. Stop when there aren't enough measurements left to create a new three-measurement sum.

In the above example, the sum of each three-measurement window is as follows:

```
A: 607 (N/A - no previous sum)
B: 618 (increased)
C: 618 (no change)
D: 617 (decreased)
E: 647 (increased)
F: 716 (increased)
G: 769 (increased)
H: 792 (increased)
```

In this example, there are 5 sums that are larger than the previous sum.

Consider sums of a three-measurement sliding window. How many sums are larger than the previous sum?

In [7]:
test_window = np.array([np.sum(test[i:(i+2)]) for i in range(len(test) - 2)])
print(test_window)
np.sum(test_window[1:] > test_window[:-1])

[399 408 418 410 407 447 509 529]


5

Also looks solid, gets same result as example explained

In [14]:
sonar_window = np.array([np.sum(sonar[i:(i+3)]) for i in range(len(sonar) - 2)])
np.sum(sonar_window[1:] > sonar_window[:-1])

1523

That was wrong (too low??)

UPDATE: of course I should have gone +3 further instead of +2... since python does not include the last element. On the other hand, the range I chose was correct, since I want to have the very last trio as well.